placeholders:
  exclamation: "!!!"
  env: "localhost"
messages:
  welcome: "Welcome from ${placeholders.env} yaml file ${placeholders.exclamation}"
  goodbye: "Good bye message from ${placeholders.env} yaml file ${placeholders.exclamation}"
management:
  endpoints:
    web:
      exposure:
        include: env, metrics
spring:
  datasource:
    url: jdbc:h2:mem:testdb
  data:
    jpa:
      repositories:
        bootstrap-mode: default
